//
//  Timings48k.swift
//  Sems
//
//  Created by Jose Luis Fernandez-Mayoralas on 26/12/18.
//  Copyright © 2018 LomoCorp. All rights reserved.
//

import Foundation

let SCANLINES_UPPER_BORDER = 64
let SCANLINES_BITMAP = 192
let SCANLINES_BOTTOM_BORDER = 56
let FIRST_VISIBLE_SCANLINE = 16
let SCANLINES_SCREEN = SCANLINES_UPPER_BORDER + SCANLINES_BITMAP + SCANLINES_BOTTOM_BORDER
let FIRST_BORDER_SCANLINE = SCANLINES_UPPER_BORDER - FIRST_VISIBLE_SCANLINE

let SCANLINE_TSTATES = 224
let FRAME_TSTATES = SCANLINE_TSTATES * SCANLINES_SCREEN

let LAST_ULA_INTERRUPT_TSTATE = 32
let FIRST_CONTENDED_TSTATE = SCANLINE_TSTATES * SCANLINES_UPPER_BORDER - 1
let LAST_CONTENDED_TSTATE = FIRST_CONTENDED_TSTATE + SCANLINES_BITMAP * 224
